package com.ohjic.batch.model;

import java.util.Date;

public class MsgQueue {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.mseq
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Integer mseq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.dstaddr
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String dstaddr;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.dstaddr_user
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String dstaddrUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.callback
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String callback;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.callback_user
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String callbackUser;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.password
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.insert_time
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Date insertTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.request_time
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Date requestTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.report_time
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Date reportTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.send_time
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Date sendTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.tcprecv_time
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Date tcprecvTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.save_time
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Date saveTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.stat
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String stat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.is_auth
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private byte[] isAuth;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.readreply
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String readreply;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.result
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String result;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.repcnt
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Integer repcnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.telecom
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String telecom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.subject
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String subject;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.fileloc1
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String fileloc1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.fileloc2
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String fileloc2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.fileloc3
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String fileloc3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.fileloc4
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String fileloc4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.fileloc5
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String fileloc5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.filesize1
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Integer filesize1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.filesize2
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Integer filesize2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.filesize3
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Integer filesize3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.filesize4
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Integer filesize4;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.filesize5
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Integer filesize5;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.filecnt_checkup
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Integer filecntCheckup;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.msg_type
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String msgType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.server_id
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String serverId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.ext_col0
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Integer extCol0;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.ext_col1
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String extCol1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.ext_col2
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String extCol2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.ext_col3
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String extCol3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.send_type
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String sendType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.dkey
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String dkey;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.dcnt
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Integer dcnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.text_type
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String textType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.expiretime
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Integer expiretime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.filecnt
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Integer filecnt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.opt_id
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String optId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.opt_cmp
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String optCmp;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.opt_post
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String optPost;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.opt_name
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String optName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.msg_charge_idx
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Integer msgChargeIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.msg_tag
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Byte msgTag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.member_IDX
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Integer memberIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.point_log_idx
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private Integer pointLogIdx;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.refunded
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String refunded;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column mail_queue.text
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	private String text;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.mseq
	 * @return  the value of mail_queue.mseq
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Integer getMseq() {
		return mseq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.mseq
	 * @param mseq  the value for mail_queue.mseq
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setMseq(Integer mseq) {
		this.mseq = mseq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.dstaddr
	 * @return  the value of mail_queue.dstaddr
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getDstaddr() {
		return dstaddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.dstaddr
	 * @param dstaddr  the value for mail_queue.dstaddr
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setDstaddr(String dstaddr) {
		this.dstaddr = dstaddr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.dstaddr_user
	 * @return  the value of mail_queue.dstaddr_user
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getDstaddrUser() {
		return dstaddrUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.dstaddr_user
	 * @param dstaddrUser  the value for mail_queue.dstaddr_user
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setDstaddrUser(String dstaddrUser) {
		this.dstaddrUser = dstaddrUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.callback
	 * @return  the value of mail_queue.callback
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getCallback() {
		return callback;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.callback
	 * @param callback  the value for mail_queue.callback
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setCallback(String callback) {
		this.callback = callback;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.callback_user
	 * @return  the value of mail_queue.callback_user
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getCallbackUser() {
		return callbackUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.callback_user
	 * @param callbackUser  the value for mail_queue.callback_user
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setCallbackUser(String callbackUser) {
		this.callbackUser = callbackUser;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.password
	 * @return  the value of mail_queue.password
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.password
	 * @param password  the value for mail_queue.password
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.insert_time
	 * @return  the value of mail_queue.insert_time
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Date getInsertTime() {
		return insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.insert_time
	 * @param insertTime  the value for mail_queue.insert_time
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.request_time
	 * @return  the value of mail_queue.request_time
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Date getRequestTime() {
		return requestTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.request_time
	 * @param requestTime  the value for mail_queue.request_time
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setRequestTime(Date requestTime) {
		this.requestTime = requestTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.report_time
	 * @return  the value of mail_queue.report_time
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Date getReportTime() {
		return reportTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.report_time
	 * @param reportTime  the value for mail_queue.report_time
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setReportTime(Date reportTime) {
		this.reportTime = reportTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.send_time
	 * @return  the value of mail_queue.send_time
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Date getSendTime() {
		return sendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.send_time
	 * @param sendTime  the value for mail_queue.send_time
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setSendTime(Date sendTime) {
		this.sendTime = sendTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.tcprecv_time
	 * @return  the value of mail_queue.tcprecv_time
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Date getTcprecvTime() {
		return tcprecvTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.tcprecv_time
	 * @param tcprecvTime  the value for mail_queue.tcprecv_time
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setTcprecvTime(Date tcprecvTime) {
		this.tcprecvTime = tcprecvTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.save_time
	 * @return  the value of mail_queue.save_time
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Date getSaveTime() {
		return saveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.save_time
	 * @param saveTime  the value for mail_queue.save_time
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setSaveTime(Date saveTime) {
		this.saveTime = saveTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.stat
	 * @return  the value of mail_queue.stat
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getStat() {
		return stat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.stat
	 * @param stat  the value for mail_queue.stat
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setStat(String stat) {
		this.stat = stat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.is_auth
	 * @return  the value of mail_queue.is_auth
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public byte[] getIsAuth() {
		return isAuth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.is_auth
	 * @param isAuth  the value for mail_queue.is_auth
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setIsAuth(byte[] isAuth) {
		this.isAuth = isAuth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.readreply
	 * @return  the value of mail_queue.readreply
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getReadreply() {
		return readreply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.readreply
	 * @param readreply  the value for mail_queue.readreply
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setReadreply(String readreply) {
		this.readreply = readreply;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.result
	 * @return  the value of mail_queue.result
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getResult() {
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.result
	 * @param result  the value for mail_queue.result
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setResult(String result) {
		this.result = result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.repcnt
	 * @return  the value of mail_queue.repcnt
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Integer getRepcnt() {
		return repcnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.repcnt
	 * @param repcnt  the value for mail_queue.repcnt
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setRepcnt(Integer repcnt) {
		this.repcnt = repcnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.telecom
	 * @return  the value of mail_queue.telecom
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getTelecom() {
		return telecom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.telecom
	 * @param telecom  the value for mail_queue.telecom
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setTelecom(String telecom) {
		this.telecom = telecom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.subject
	 * @return  the value of mail_queue.subject
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getSubject() {
		return subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.subject
	 * @param subject  the value for mail_queue.subject
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setSubject(String subject) {
		this.subject = subject;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.fileloc1
	 * @return  the value of mail_queue.fileloc1
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getFileloc1() {
		return fileloc1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.fileloc1
	 * @param fileloc1  the value for mail_queue.fileloc1
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setFileloc1(String fileloc1) {
		this.fileloc1 = fileloc1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.fileloc2
	 * @return  the value of mail_queue.fileloc2
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getFileloc2() {
		return fileloc2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.fileloc2
	 * @param fileloc2  the value for mail_queue.fileloc2
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setFileloc2(String fileloc2) {
		this.fileloc2 = fileloc2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.fileloc3
	 * @return  the value of mail_queue.fileloc3
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getFileloc3() {
		return fileloc3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.fileloc3
	 * @param fileloc3  the value for mail_queue.fileloc3
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setFileloc3(String fileloc3) {
		this.fileloc3 = fileloc3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.fileloc4
	 * @return  the value of mail_queue.fileloc4
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getFileloc4() {
		return fileloc4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.fileloc4
	 * @param fileloc4  the value for mail_queue.fileloc4
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setFileloc4(String fileloc4) {
		this.fileloc4 = fileloc4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.fileloc5
	 * @return  the value of mail_queue.fileloc5
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getFileloc5() {
		return fileloc5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.fileloc5
	 * @param fileloc5  the value for mail_queue.fileloc5
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setFileloc5(String fileloc5) {
		this.fileloc5 = fileloc5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.filesize1
	 * @return  the value of mail_queue.filesize1
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Integer getFilesize1() {
		return filesize1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.filesize1
	 * @param filesize1  the value for mail_queue.filesize1
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setFilesize1(Integer filesize1) {
		this.filesize1 = filesize1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.filesize2
	 * @return  the value of mail_queue.filesize2
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Integer getFilesize2() {
		return filesize2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.filesize2
	 * @param filesize2  the value for mail_queue.filesize2
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setFilesize2(Integer filesize2) {
		this.filesize2 = filesize2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.filesize3
	 * @return  the value of mail_queue.filesize3
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Integer getFilesize3() {
		return filesize3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.filesize3
	 * @param filesize3  the value for mail_queue.filesize3
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setFilesize3(Integer filesize3) {
		this.filesize3 = filesize3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.filesize4
	 * @return  the value of mail_queue.filesize4
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Integer getFilesize4() {
		return filesize4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.filesize4
	 * @param filesize4  the value for mail_queue.filesize4
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setFilesize4(Integer filesize4) {
		this.filesize4 = filesize4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.filesize5
	 * @return  the value of mail_queue.filesize5
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Integer getFilesize5() {
		return filesize5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.filesize5
	 * @param filesize5  the value for mail_queue.filesize5
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setFilesize5(Integer filesize5) {
		this.filesize5 = filesize5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.filecnt_checkup
	 * @return  the value of mail_queue.filecnt_checkup
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Integer getFilecntCheckup() {
		return filecntCheckup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.filecnt_checkup
	 * @param filecntCheckup  the value for mail_queue.filecnt_checkup
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setFilecntCheckup(Integer filecntCheckup) {
		this.filecntCheckup = filecntCheckup;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.msg_type
	 * @return  the value of mail_queue.msg_type
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getMsgType() {
		return msgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.msg_type
	 * @param msgType  the value for mail_queue.msg_type
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setMsgType(String msgType) {
		this.msgType = msgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.server_id
	 * @return  the value of mail_queue.server_id
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getServerId() {
		return serverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.server_id
	 * @param serverId  the value for mail_queue.server_id
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setServerId(String serverId) {
		this.serverId = serverId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.ext_col0
	 * @return  the value of mail_queue.ext_col0
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Integer getExtCol0() {
		return extCol0;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.ext_col0
	 * @param extCol0  the value for mail_queue.ext_col0
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setExtCol0(Integer extCol0) {
		this.extCol0 = extCol0;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.ext_col1
	 * @return  the value of mail_queue.ext_col1
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getExtCol1() {
		return extCol1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.ext_col1
	 * @param extCol1  the value for mail_queue.ext_col1
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setExtCol1(String extCol1) {
		this.extCol1 = extCol1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.ext_col2
	 * @return  the value of mail_queue.ext_col2
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getExtCol2() {
		return extCol2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.ext_col2
	 * @param extCol2  the value for mail_queue.ext_col2
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setExtCol2(String extCol2) {
		this.extCol2 = extCol2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.ext_col3
	 * @return  the value of mail_queue.ext_col3
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getExtCol3() {
		return extCol3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.ext_col3
	 * @param extCol3  the value for mail_queue.ext_col3
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setExtCol3(String extCol3) {
		this.extCol3 = extCol3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.send_type
	 * @return  the value of mail_queue.send_type
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getSendType() {
		return sendType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.send_type
	 * @param sendType  the value for mail_queue.send_type
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setSendType(String sendType) {
		this.sendType = sendType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.dkey
	 * @return  the value of mail_queue.dkey
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getDkey() {
		return dkey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.dkey
	 * @param dkey  the value for mail_queue.dkey
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setDkey(String dkey) {
		this.dkey = dkey;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.dcnt
	 * @return  the value of mail_queue.dcnt
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Integer getDcnt() {
		return dcnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.dcnt
	 * @param dcnt  the value for mail_queue.dcnt
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setDcnt(Integer dcnt) {
		this.dcnt = dcnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.text_type
	 * @return  the value of mail_queue.text_type
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getTextType() {
		return textType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.text_type
	 * @param textType  the value for mail_queue.text_type
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setTextType(String textType) {
		this.textType = textType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.expiretime
	 * @return  the value of mail_queue.expiretime
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Integer getExpiretime() {
		return expiretime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.expiretime
	 * @param expiretime  the value for mail_queue.expiretime
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setExpiretime(Integer expiretime) {
		this.expiretime = expiretime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.filecnt
	 * @return  the value of mail_queue.filecnt
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Integer getFilecnt() {
		return filecnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.filecnt
	 * @param filecnt  the value for mail_queue.filecnt
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setFilecnt(Integer filecnt) {
		this.filecnt = filecnt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.opt_id
	 * @return  the value of mail_queue.opt_id
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getOptId() {
		return optId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.opt_id
	 * @param optId  the value for mail_queue.opt_id
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setOptId(String optId) {
		this.optId = optId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.opt_cmp
	 * @return  the value of mail_queue.opt_cmp
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getOptCmp() {
		return optCmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.opt_cmp
	 * @param optCmp  the value for mail_queue.opt_cmp
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setOptCmp(String optCmp) {
		this.optCmp = optCmp;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.opt_post
	 * @return  the value of mail_queue.opt_post
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getOptPost() {
		return optPost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.opt_post
	 * @param optPost  the value for mail_queue.opt_post
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setOptPost(String optPost) {
		this.optPost = optPost;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.opt_name
	 * @return  the value of mail_queue.opt_name
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getOptName() {
		return optName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.opt_name
	 * @param optName  the value for mail_queue.opt_name
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setOptName(String optName) {
		this.optName = optName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.msg_charge_idx
	 * @return  the value of mail_queue.msg_charge_idx
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Integer getMsgChargeIdx() {
		return msgChargeIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.msg_charge_idx
	 * @param msgChargeIdx  the value for mail_queue.msg_charge_idx
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setMsgChargeIdx(Integer msgChargeIdx) {
		this.msgChargeIdx = msgChargeIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.msg_tag
	 * @return  the value of mail_queue.msg_tag
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Byte getMsgTag() {
		return msgTag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.msg_tag
	 * @param msgTag  the value for mail_queue.msg_tag
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setMsgTag(Byte msgTag) {
		this.msgTag = msgTag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.member_IDX
	 * @return  the value of mail_queue.member_IDX
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Integer getMemberIdx() {
		return memberIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.member_IDX
	 * @param memberIdx  the value for mail_queue.member_IDX
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setMemberIdx(Integer memberIdx) {
		this.memberIdx = memberIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.point_log_idx
	 * @return  the value of mail_queue.point_log_idx
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public Integer getPointLogIdx() {
		return pointLogIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.point_log_idx
	 * @param pointLogIdx  the value for mail_queue.point_log_idx
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setPointLogIdx(Integer pointLogIdx) {
		this.pointLogIdx = pointLogIdx;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.refunded
	 * @return  the value of mail_queue.refunded
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getRefunded() {
		return refunded;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.refunded
	 * @param refunded  the value for mail_queue.refunded
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setRefunded(String refunded) {
		this.refunded = refunded;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column mail_queue.text
	 * @return  the value of mail_queue.text
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public String getText() {
		return text;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column mail_queue.text
	 * @param text  the value for mail_queue.text
	 * @mbg.generated  Thu Feb 02 11:24:24 KST 2017
	 */
	public void setText(String text) {
		this.text = text;
	}
}