package com.wadiz.client.persistence;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.wadiz.client.model.ClientResponse;
import com.wadiz.client.model.ClientResponseExample;

public interface ClientResponseMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table response
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	int countByExample(ClientResponseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table response
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	int deleteByExample(ClientResponseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table response
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	int deleteByPrimaryKey(Long responseSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table response
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	int insert(ClientResponse record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table response
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	int insertSelective(ClientResponse record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table response
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	List<ClientResponse> selectByExample(ClientResponseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table response
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	ClientResponse selectByPrimaryKey(Long responseSeq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table response
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	int updateByExampleSelective(@Param("record") ClientResponse record, @Param("example") ClientResponseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table response
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	int updateByExample(@Param("record") ClientResponse record, @Param("example") ClientResponseExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table response
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	int updateByPrimaryKeySelective(ClientResponse record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table response
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	int updateByPrimaryKey(ClientResponse record);
}