package com.wadiz.client.ibk.batch.model;

import java.util.Date;

public class TbIbkInvestCancelIfInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbIbkInvestCancelIfInfo.InvestId
	 * @mbggenerated  Wed Jan 20 12:10:05 KST 2016
	 */
	private Integer investId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbIbkInvestCancelIfInfo.Stat
	 * @mbggenerated  Wed Jan 20 12:10:05 KST 2016
	 */
	private String stat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbIbkInvestCancelIfInfo.RegDate
	 * @mbggenerated  Wed Jan 20 12:10:05 KST 2016
	 */
	private Date regDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbIbkInvestCancelIfInfo.ReqDate
	 * @mbggenerated  Wed Jan 20 12:10:05 KST 2016
	 */
	private Date reqDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbIbkInvestCancelIfInfo.ResDate
	 * @mbggenerated  Wed Jan 20 12:10:05 KST 2016
	 */
	private Date resDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbIbkInvestCancelIfInfo.InvestId
	 * @return  the value of TbIbkInvestCancelIfInfo.InvestId
	 * @mbggenerated  Wed Jan 20 12:10:05 KST 2016
	 */
	public Integer getInvestId() {
		return investId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbIbkInvestCancelIfInfo.InvestId
	 * @param investId  the value for TbIbkInvestCancelIfInfo.InvestId
	 * @mbggenerated  Wed Jan 20 12:10:05 KST 2016
	 */
	public void setInvestId(Integer investId) {
		this.investId = investId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbIbkInvestCancelIfInfo.Stat
	 * @return  the value of TbIbkInvestCancelIfInfo.Stat
	 * @mbggenerated  Wed Jan 20 12:10:05 KST 2016
	 */
	public String getStat() {
		return stat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbIbkInvestCancelIfInfo.Stat
	 * @param stat  the value for TbIbkInvestCancelIfInfo.Stat
	 * @mbggenerated  Wed Jan 20 12:10:05 KST 2016
	 */
	public void setStat(String stat) {
		this.stat = stat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbIbkInvestCancelIfInfo.RegDate
	 * @return  the value of TbIbkInvestCancelIfInfo.RegDate
	 * @mbggenerated  Wed Jan 20 12:10:05 KST 2016
	 */
	public Date getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbIbkInvestCancelIfInfo.RegDate
	 * @param regDate  the value for TbIbkInvestCancelIfInfo.RegDate
	 * @mbggenerated  Wed Jan 20 12:10:05 KST 2016
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbIbkInvestCancelIfInfo.ReqDate
	 * @return  the value of TbIbkInvestCancelIfInfo.ReqDate
	 * @mbggenerated  Wed Jan 20 12:10:05 KST 2016
	 */
	public Date getReqDate() {
		return reqDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbIbkInvestCancelIfInfo.ReqDate
	 * @param reqDate  the value for TbIbkInvestCancelIfInfo.ReqDate
	 * @mbggenerated  Wed Jan 20 12:10:05 KST 2016
	 */
	public void setReqDate(Date reqDate) {
		this.reqDate = reqDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbIbkInvestCancelIfInfo.ResDate
	 * @return  the value of TbIbkInvestCancelIfInfo.ResDate
	 * @mbggenerated  Wed Jan 20 12:10:05 KST 2016
	 */
	public Date getResDate() {
		return resDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbIbkInvestCancelIfInfo.ResDate
	 * @param resDate  the value for TbIbkInvestCancelIfInfo.ResDate
	 * @mbggenerated  Wed Jan 20 12:10:05 KST 2016
	 */
	public void setResDate(Date resDate) {
		this.resDate = resDate;
	}
}