package com.wadiz.client.ibk.batch.model;

import java.util.Date;

public class TbInvest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.InvestId
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private Integer investId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.CampaignId
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private Integer campaignId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.SecurtId
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private Integer securtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.Qty
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private Integer qty;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.InvestAmount
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private Long investAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.Charge
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private Long charge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.TotalAmount
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private Long totalAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.Oid
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private String oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.KsdLinkedYn
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private String ksdLinkedYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.DepositYn
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private String depositYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.TxBankCode
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private String txBankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.TxAccountNo
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private String txAccountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.IssConfirmYn
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private String issConfirmYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.UserIvstSt
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private String userIvstSt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.DpsOrgnztn
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private String dpsOrgnztn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.KsfcTrIdnId
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private String ksfcTrIdnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.UserId
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.RegDate
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private Date regDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.UpdateDate
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.PayDate
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private String payDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbInvest.ShowName
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    private String showName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.InvestId
     *
     * @return the value of TbInvest.InvestId
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public Integer getInvestId() {
        return investId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.InvestId
     *
     * @param investId the value for TbInvest.InvestId
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setInvestId(Integer investId) {
        this.investId = investId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.CampaignId
     *
     * @return the value of TbInvest.CampaignId
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public Integer getCampaignId() {
        return campaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.CampaignId
     *
     * @param campaignId the value for TbInvest.CampaignId
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setCampaignId(Integer campaignId) {
        this.campaignId = campaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.SecurtId
     *
     * @return the value of TbInvest.SecurtId
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public Integer getSecurtId() {
        return securtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.SecurtId
     *
     * @param securtId the value for TbInvest.SecurtId
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setSecurtId(Integer securtId) {
        this.securtId = securtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.Qty
     *
     * @return the value of TbInvest.Qty
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public Integer getQty() {
        return qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.Qty
     *
     * @param qty the value for TbInvest.Qty
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setQty(Integer qty) {
        this.qty = qty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.InvestAmount
     *
     * @return the value of TbInvest.InvestAmount
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public Long getInvestAmount() {
        return investAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.InvestAmount
     *
     * @param investAmount the value for TbInvest.InvestAmount
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setInvestAmount(Long investAmount) {
        this.investAmount = investAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.Charge
     *
     * @return the value of TbInvest.Charge
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public Long getCharge() {
        return charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.Charge
     *
     * @param charge the value for TbInvest.Charge
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setCharge(Long charge) {
        this.charge = charge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.TotalAmount
     *
     * @return the value of TbInvest.TotalAmount
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public Long getTotalAmount() {
        return totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.TotalAmount
     *
     * @param totalAmount the value for TbInvest.TotalAmount
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setTotalAmount(Long totalAmount) {
        this.totalAmount = totalAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.Oid
     *
     * @return the value of TbInvest.Oid
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.Oid
     *
     * @param oid the value for TbInvest.Oid
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setOid(String oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.KsdLinkedYn
     *
     * @return the value of TbInvest.KsdLinkedYn
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public String getKsdLinkedYn() {
        return ksdLinkedYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.KsdLinkedYn
     *
     * @param ksdLinkedYn the value for TbInvest.KsdLinkedYn
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setKsdLinkedYn(String ksdLinkedYn) {
        this.ksdLinkedYn = ksdLinkedYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.DepositYn
     *
     * @return the value of TbInvest.DepositYn
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public String getDepositYn() {
        return depositYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.DepositYn
     *
     * @param depositYn the value for TbInvest.DepositYn
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setDepositYn(String depositYn) {
        this.depositYn = depositYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.TxBankCode
     *
     * @return the value of TbInvest.TxBankCode
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public String getTxBankCode() {
        return txBankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.TxBankCode
     *
     * @param txBankCode the value for TbInvest.TxBankCode
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setTxBankCode(String txBankCode) {
        this.txBankCode = txBankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.TxAccountNo
     *
     * @return the value of TbInvest.TxAccountNo
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public String getTxAccountNo() {
        return txAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.TxAccountNo
     *
     * @param txAccountNo the value for TbInvest.TxAccountNo
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setTxAccountNo(String txAccountNo) {
        this.txAccountNo = txAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.IssConfirmYn
     *
     * @return the value of TbInvest.IssConfirmYn
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public String getIssConfirmYn() {
        return issConfirmYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.IssConfirmYn
     *
     * @param issConfirmYn the value for TbInvest.IssConfirmYn
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setIssConfirmYn(String issConfirmYn) {
        this.issConfirmYn = issConfirmYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.UserIvstSt
     *
     * @return the value of TbInvest.UserIvstSt
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public String getUserIvstSt() {
        return userIvstSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.UserIvstSt
     *
     * @param userIvstSt the value for TbInvest.UserIvstSt
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setUserIvstSt(String userIvstSt) {
        this.userIvstSt = userIvstSt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.DpsOrgnztn
     *
     * @return the value of TbInvest.DpsOrgnztn
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public String getDpsOrgnztn() {
        return dpsOrgnztn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.DpsOrgnztn
     *
     * @param dpsOrgnztn the value for TbInvest.DpsOrgnztn
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setDpsOrgnztn(String dpsOrgnztn) {
        this.dpsOrgnztn = dpsOrgnztn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.KsfcTrIdnId
     *
     * @return the value of TbInvest.KsfcTrIdnId
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public String getKsfcTrIdnId() {
        return ksfcTrIdnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.KsfcTrIdnId
     *
     * @param ksfcTrIdnId the value for TbInvest.KsfcTrIdnId
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setKsfcTrIdnId(String ksfcTrIdnId) {
        this.ksfcTrIdnId = ksfcTrIdnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.UserId
     *
     * @return the value of TbInvest.UserId
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.UserId
     *
     * @param userId the value for TbInvest.UserId
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.RegDate
     *
     * @return the value of TbInvest.RegDate
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.RegDate
     *
     * @param regDate the value for TbInvest.RegDate
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.UpdateDate
     *
     * @return the value of TbInvest.UpdateDate
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.UpdateDate
     *
     * @param updateDate the value for TbInvest.UpdateDate
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.PayDate
     *
     * @return the value of TbInvest.PayDate
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public String getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.PayDate
     *
     * @param payDate the value for TbInvest.PayDate
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setPayDate(String payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbInvest.ShowName
     *
     * @return the value of TbInvest.ShowName
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public String getShowName() {
        return showName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbInvest.ShowName
     *
     * @param showName the value for TbInvest.ShowName
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    public void setShowName(String showName) {
        this.showName = showName;
    }
}