package com.ohjic.batch.persistence;

import java.util.List;

import com.ohjic.batch.model.MsgQueue;

public interface MsgQueueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_queue
     *
     * @mbg.generated Wed Feb 01 15:16:34 KST 2017
     */
    int deleteByPrimaryKey(Integer mseq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_queue
     *
     * @mbg.generated Wed Feb 01 15:16:34 KST 2017
     */
    int insert(MsgQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_queue
     *
     * @mbg.generated Wed Feb 01 15:16:34 KST 2017
     */
    int insertSelective(MsgQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_queue
     *
     * @mbg.generated Wed Feb 01 15:16:34 KST 2017
     */
    MsgQueue selectByPrimaryKey(Integer mseq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_queue
     *
     * @mbg.generated Wed Feb 01 15:16:34 KST 2017
     */
    int updateByPrimaryKeySelective(MsgQueue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_queue
     *
     * @mbg.generated Wed Feb 01 15:16:34 KST 2017
     */
    int updateByPrimaryKey(MsgQueue record);
    
    List<MsgQueue> selectMsgQueueListByStat(String stat);
}