package com.ohjic.batch.persistence;

import com.ohjic.batch.model.MsgResult;

public interface MsgResultMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail_result
	 * @mbg.generated  Thu Feb 02 16:28:25 KST 2017
	 */
	int deleteByPrimaryKey(Integer mseq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail_result
	 * @mbg.generated  Thu Feb 02 16:28:25 KST 2017
	 */
	int insert(MsgResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail_result
	 * @mbg.generated  Thu Feb 02 16:28:25 KST 2017
	 */
	int insertSelective(MsgResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail_result
	 * @mbg.generated  Thu Feb 02 16:28:25 KST 2017
	 */
	MsgResult selectByPrimaryKey(Integer mseq);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail_result
	 * @mbg.generated  Thu Feb 02 16:28:25 KST 2017
	 */
	int updateByPrimaryKeySelective(MsgResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail_result
	 * @mbg.generated  Thu Feb 02 16:28:25 KST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(MsgResult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table mail_result
	 * @mbg.generated  Thu Feb 02 16:28:25 KST 2017
	 */
	int updateByPrimaryKey(MsgResult record);
}