package com.ohjic.batch.persistence;

import com.ohjic.batch.model.MsgResult;

public interface MsgResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_result
     *
     * @mbg.generated Wed Feb 01 15:16:34 KST 2017
     */
    int insert(MsgResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table msg_result
     *
     * @mbg.generated Wed Feb 01 15:16:34 KST 2017
     */
    int insertSelective(MsgResult record);
}