package com.wadiz.client.ibk.batch.model;

import java.util.Date;

public class TbIbkInvestRefundIfInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbIbkInvestRefundIfInfo.RefundId
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	private Integer refundId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbIbkInvestRefundIfInfo.InvestId
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	private Integer investId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbIbkInvestRefundIfInfo.Stat
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	private String stat;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbIbkInvestRefundIfInfo.ResnCode
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	private String resnCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbIbkInvestRefundIfInfo.RefundCode
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	private String refundCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbIbkInvestRefundIfInfo.RegDate
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	private Date regDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbIbkInvestRefundIfInfo.ReqDate
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	private Date reqDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column TbIbkInvestRefundIfInfo.ResDate
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	private Date resDate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbIbkInvestRefundIfInfo.RefundId
	 * @return  the value of TbIbkInvestRefundIfInfo.RefundId
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	public Integer getRefundId() {
		return refundId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbIbkInvestRefundIfInfo.RefundId
	 * @param refundId  the value for TbIbkInvestRefundIfInfo.RefundId
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	public void setRefundId(Integer refundId) {
		this.refundId = refundId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbIbkInvestRefundIfInfo.InvestId
	 * @return  the value of TbIbkInvestRefundIfInfo.InvestId
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	public Integer getInvestId() {
		return investId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbIbkInvestRefundIfInfo.InvestId
	 * @param investId  the value for TbIbkInvestRefundIfInfo.InvestId
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	public void setInvestId(Integer investId) {
		this.investId = investId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbIbkInvestRefundIfInfo.Stat
	 * @return  the value of TbIbkInvestRefundIfInfo.Stat
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	public String getStat() {
		return stat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbIbkInvestRefundIfInfo.Stat
	 * @param stat  the value for TbIbkInvestRefundIfInfo.Stat
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	public void setStat(String stat) {
		this.stat = stat;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbIbkInvestRefundIfInfo.ResnCode
	 * @return  the value of TbIbkInvestRefundIfInfo.ResnCode
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	public String getResnCode() {
		return resnCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbIbkInvestRefundIfInfo.ResnCode
	 * @param resnCode  the value for TbIbkInvestRefundIfInfo.ResnCode
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	public void setResnCode(String resnCode) {
		this.resnCode = resnCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbIbkInvestRefundIfInfo.RefundCode
	 * @return  the value of TbIbkInvestRefundIfInfo.RefundCode
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	public String getRefundCode() {
		return refundCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbIbkInvestRefundIfInfo.RefundCode
	 * @param refundCode  the value for TbIbkInvestRefundIfInfo.RefundCode
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	public void setRefundCode(String refundCode) {
		this.refundCode = refundCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbIbkInvestRefundIfInfo.RegDate
	 * @return  the value of TbIbkInvestRefundIfInfo.RegDate
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	public Date getRegDate() {
		return regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbIbkInvestRefundIfInfo.RegDate
	 * @param regDate  the value for TbIbkInvestRefundIfInfo.RegDate
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	public void setRegDate(Date regDate) {
		this.regDate = regDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbIbkInvestRefundIfInfo.ReqDate
	 * @return  the value of TbIbkInvestRefundIfInfo.ReqDate
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	public Date getReqDate() {
		return reqDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbIbkInvestRefundIfInfo.ReqDate
	 * @param reqDate  the value for TbIbkInvestRefundIfInfo.ReqDate
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	public void setReqDate(Date reqDate) {
		this.reqDate = reqDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column TbIbkInvestRefundIfInfo.ResDate
	 * @return  the value of TbIbkInvestRefundIfInfo.ResDate
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	public Date getResDate() {
		return resDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column TbIbkInvestRefundIfInfo.ResDate
	 * @param resDate  the value for TbIbkInvestRefundIfInfo.ResDate
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	public void setResDate(Date resDate) {
		this.resDate = resDate;
	}
}