package com.wadiz.client.ibk.batch.model;

public class TbServiceHolidayInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbServiceHolidayInfo.YYYY
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbServiceHolidayInfo.MM
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    private String month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbServiceHolidayInfo.DD
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    private String day;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbServiceHolidayInfo.YYYY
     *
     * @return the value of TbServiceHolidayInfo.YYYY
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbServiceHolidayInfo.YYYY
     *
     * @param year the value for TbServiceHolidayInfo.YYYY
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    public void setYear(String year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbServiceHolidayInfo.MM
     *
     * @return the value of TbServiceHolidayInfo.MM
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbServiceHolidayInfo.MM
     *
     * @param month the value for TbServiceHolidayInfo.MM
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    public void setMonth(String month) {
        this.month = month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbServiceHolidayInfo.DD
     *
     * @return the value of TbServiceHolidayInfo.DD
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbServiceHolidayInfo.DD
     *
     * @param day the value for TbServiceHolidayInfo.DD
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    public void setDay(String day) {
        this.day = day;
    }
}