CREATE DATABASE IF NOT EXISTS `batch` /*!40100 DEFAULT CHARACTER SET utf8 */;
USE `batch`;

CREATE TABLE `mail_queue` (
	`mseq` INT(13) NOT NULL AUTO_INCREMENT COMMENT '메일SEQ',
	`dstaddr` VARCHAR(100) NOT NULL COMMENT '수신 메일주소',
	`dstaddr_user` VARCHAR(100) NOT NULL COMMENT '수신자 이름',
	`callback` VARCHAR(100) NOT NULL COMMENT '발신 메일주소',
	`callback_user` VARCHAR(100) NOT NULL COMMENT '발신자 이름',
	`password` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '인증사용시 메일비밀번호',
	`text` TEXT NOT NULL COMMENT '메일 본문',
	`insert_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'insert 시간',
	`request_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '발송요청 시간(예약전송일 경우 미래시간으로 설정)',
	`report_time` DATETIME NULL DEFAULT NULL,
	`send_time` DATETIME NULL DEFAULT NULL COMMENT '실제 발송시간',
	`tcprecv_time` DATETIME NULL DEFAULT NULL COMMENT '결과 받은 시간',
	`save_time` DATETIME NULL DEFAULT NULL COMMENT 'DB 저장시간',
	`stat` CHAR(1) NOT NULL DEFAULT '0' COMMENT '전송상태(0:전송대기, 1:송신중, 2:송신완료, 3:결과수신)',
	`is_auth` CHAR(1) NOT NULL DEFAULT '0' COMMENT '인증여부(0:미인증, 1:인증(인증 시에 메일계정 비밀번호 설정))',
	`is_reserved` CHAR(1) NOT NULL DEFAULT '0' COMMENT '예약전송여부(0:일반전송, 1:예약전송)',
	`readreply` CHAR(1) NULL DEFAULT NULL,
	`result` CHAR(4) NULL DEFAULT NULL COMMENT '결과코드(0000:성공, 0001:취소, 9999:실패)',
	`repcnt` INT(11) NOT NULL DEFAULT '0',
	`telecom` VARCHAR(10) NULL DEFAULT NULL,
	`subject` VARCHAR(200) NULL DEFAULT ' ' COMMENT '메일제목',
	`fileloc1` VARCHAR(512) NULL DEFAULT NULL,
	`fileloc2` VARCHAR(512) NULL DEFAULT NULL,
	`fileloc3` VARCHAR(512) NULL DEFAULT NULL,
	`fileloc4` VARCHAR(512) NULL DEFAULT NULL,
	`fileloc5` VARCHAR(512) NULL DEFAULT NULL,
	`filesize1` INT(11) NULL DEFAULT NULL,
	`filesize2` INT(11) NULL DEFAULT NULL,
	`filesize3` INT(11) NULL DEFAULT NULL,
	`filesize4` INT(11) NULL DEFAULT NULL,
	`filesize5` INT(11) NULL DEFAULT NULL,
	`filecnt_checkup` INT(11) NOT NULL DEFAULT '0',
	`msg_type` CHAR(1) NOT NULL DEFAULT '1',
	`server_id` VARCHAR(40) NULL DEFAULT NULL COMMENT '서버ID',
	`ext_col0` INT(11) NULL DEFAULT NULL COMMENT 'churchCode',
	`ext_col1` VARCHAR(64) NULL DEFAULT NULL,
	`ext_col2` VARCHAR(32) NULL DEFAULT NULL,
	`ext_col3` VARCHAR(32) NULL DEFAULT NULL,
	`send_type` CHAR(1) NOT NULL DEFAULT '1' COMMENT '전송구분(1:동보, 2:비동보)',
	`dkey` VARCHAR(50) NOT NULL DEFAULT '0',
	`dcnt` INT(11) NOT NULL DEFAULT '0',
	`text_type` CHAR(1) NOT NULL DEFAULT '0',
	`expiretime` INT(11) NULL DEFAULT '86400',
	`filecnt` INT(11) NOT NULL DEFAULT '0',
	`opt_id` VARCHAR(20) NULL DEFAULT NULL COMMENT '보낸 사람 아이디',
	`opt_cmp` VARCHAR(40) NULL DEFAULT NULL,
	`opt_post` VARCHAR(40) NULL DEFAULT NULL,
	`opt_name` VARCHAR(40) NULL DEFAULT NULL,
	`msg_charge_idx` INT(11) NOT NULL DEFAULT '0',
	`msg_tag` TINYINT(11) NOT NULL DEFAULT '0',
	`member_IDX` INT(11) NOT NULL DEFAULT '0',
	`point_log_idx` INT(11) NOT NULL DEFAULT '0',
	`refunded` ENUM('N','Y') NOT NULL DEFAULT 'N',
	PRIMARY KEY (`mseq`),
	INDEX `IDX_msg_queue_sel` (`stat`, `request_time`, `msg_type`),
	INDEX `ext_col4` (`msg_charge_idx`, `msg_tag`),
	INDEX `member_idx` (`member_IDX`),
	INDEX `point_log_idx` (`point_log_idx`),
	INDEX `opt_id` (`opt_id`)
)
COMMENT='메일 큐테이블'
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;


CREATE TABLE `mail_result` (
	`mseq` INT(13) NOT NULL AUTO_INCREMENT COMMENT '메일SEQ',
	`dstaddr` VARCHAR(100) NOT NULL COMMENT '수신 메일주소',
	`dstaddr_user` VARCHAR(100) NOT NULL COMMENT '수신자 이름',
	`callback` VARCHAR(100) NOT NULL COMMENT '발신 메일주소',
	`callback_user` VARCHAR(100) NOT NULL COMMENT '발신자 이름',
	`password` VARCHAR(100) NOT NULL COMMENT '인증사용시 메일비밀번호',
	`text` TEXT NOT NULL COMMENT '메일 본문',
	`insert_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'insert 시간',
	`request_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '발송요청 시간(예약전송일 경우 미래시간으로 설정)',
	`report_time` DATETIME NULL DEFAULT NULL,
	`send_time` DATETIME NULL DEFAULT NULL COMMENT '실제 발송시간',
	`tcprecv_time` DATETIME NULL DEFAULT NULL COMMENT '결과 받은 시간',
	`save_time` DATETIME NULL DEFAULT NULL COMMENT 'DB 저장시간',
	`stat` CHAR(1) NOT NULL DEFAULT '0' COMMENT '전송상태(0:전송대기, 1:송신중, 2:송신완료, 3:결과수신)',
	`is_auth` CHAR(1) NOT NULL DEFAULT '0' COMMENT '인증여부(0:미인증, 1:인증(인증 시에 메일계정 비밀번호 설정))',
	`is_reserved` CHAR(1) NOT NULL DEFAULT '0' COMMENT '예약전송여부(0:일반전송, 1:예약전송)',
	`readreply` CHAR(1) NULL DEFAULT NULL,
	`result` CHAR(4) NULL DEFAULT NULL COMMENT '결과코드(0000:성공, 0001:취소, 9999:실패)',
	`repcnt` INT(11) NOT NULL DEFAULT '0',
	`telecom` VARCHAR(10) NULL DEFAULT NULL,
	`subject` VARCHAR(200) NULL DEFAULT ' ' COMMENT '메일제목',
	`fileloc1` VARCHAR(512) NULL DEFAULT NULL,
	`fileloc2` VARCHAR(512) NULL DEFAULT NULL,
	`fileloc3` VARCHAR(512) NULL DEFAULT NULL,
	`fileloc4` VARCHAR(512) NULL DEFAULT NULL,
	`fileloc5` VARCHAR(512) NULL DEFAULT NULL,
	`filesize1` INT(11) NULL DEFAULT NULL,
	`filesize2` INT(11) NULL DEFAULT NULL,
	`filesize3` INT(11) NULL DEFAULT NULL,
	`filesize4` INT(11) NULL DEFAULT NULL,
	`filesize5` INT(11) NULL DEFAULT NULL,
	`filecnt_checkup` INT(11) NOT NULL DEFAULT '0',
	`msg_type` CHAR(1) NOT NULL DEFAULT '1',
	`server_id` VARCHAR(40) NULL DEFAULT NULL COMMENT '서버ID',
	`ext_col0` INT(11) NULL DEFAULT NULL COMMENT 'churchCode',
	`ext_col1` VARCHAR(64) NULL DEFAULT NULL,
	`ext_col2` VARCHAR(32) NULL DEFAULT NULL,
	`ext_col3` VARCHAR(32) NULL DEFAULT NULL,
	`send_type` CHAR(1) NOT NULL DEFAULT '1' COMMENT '전송구분(1:동보, 2:비동보)',
	`dkey` VARCHAR(50) NOT NULL DEFAULT '0',
	`dcnt` INT(11) NOT NULL DEFAULT '0',
	`text_type` CHAR(1) NOT NULL DEFAULT '0',
	`expiretime` INT(11) NULL DEFAULT '86400',
	`filecnt` INT(11) NOT NULL DEFAULT '0',
	`opt_id` VARCHAR(20) NULL DEFAULT NULL COMMENT '보낸 사람 아이디',
	`opt_cmp` VARCHAR(40) NULL DEFAULT NULL,
	`opt_post` VARCHAR(40) NULL DEFAULT NULL,
	`opt_name` VARCHAR(40) NULL DEFAULT NULL,
	`msg_charge_idx` INT(11) NOT NULL DEFAULT '0',
	`msg_tag` TINYINT(11) NOT NULL DEFAULT '0',
	`member_IDX` INT(11) NOT NULL DEFAULT '0',
	`point_log_idx` INT(11) NOT NULL DEFAULT '0',
	`refunded` ENUM('N','Y') NOT NULL DEFAULT 'N',
	INDEX `IDX_msg_queue_sel` (`stat`, `request_time`, `msg_type`),
	INDEX `ext_col4` (`msg_charge_idx`, `msg_tag`),
	INDEX `member_idx` (`member_IDX`),
	INDEX `point_log_idx` (`point_log_idx`),
	INDEX `opt_id` (`opt_id`),
	INDEX `mseq` (`mseq`)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB
AUTO_INCREMENT=1
;

