package com.wadiz.client.ibk.batch.model;

import java.util.Date;

public class TbServiceHolidayInfo extends TbServiceHolidayInfoKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbServiceHolidayInfo.UseYn
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    private String useYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbServiceHolidayInfo.Description
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbServiceHolidayInfo.RegDate
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    private Date regDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbServiceHolidayInfo.UseYn
     *
     * @return the value of TbServiceHolidayInfo.UseYn
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    public String getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbServiceHolidayInfo.UseYn
     *
     * @param useYn the value for TbServiceHolidayInfo.UseYn
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    public void setUseYn(String useYn) {
        this.useYn = useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbServiceHolidayInfo.Description
     *
     * @return the value of TbServiceHolidayInfo.Description
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbServiceHolidayInfo.Description
     *
     * @param description the value for TbServiceHolidayInfo.Description
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbServiceHolidayInfo.RegDate
     *
     * @return the value of TbServiceHolidayInfo.RegDate
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbServiceHolidayInfo.RegDate
     *
     * @param regDate the value for TbServiceHolidayInfo.RegDate
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }
}