package com.wadiz.client.ibk.batch.model;

import java.util.Date;

public class TbIbkBatchWokingDay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkBatchWokingDay.WorkingNo
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    private Integer workingNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkBatchWokingDay.WorkingDate
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    private String workingDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkBatchWokingDay.ProcStatus
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    private String procStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkBatchWokingDay.RegDate
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    private Date regDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkBatchWokingDay.UpdateDate
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkBatchWokingDay.WorkingNo
     *
     * @return the value of TbIbkBatchWokingDay.WorkingNo
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    public Integer getWorkingNo() {
        return workingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkBatchWokingDay.WorkingNo
     *
     * @param workingNo the value for TbIbkBatchWokingDay.WorkingNo
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    public void setWorkingNo(Integer workingNo) {
        this.workingNo = workingNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkBatchWokingDay.WorkingDate
     *
     * @return the value of TbIbkBatchWokingDay.WorkingDate
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    public String getWorkingDate() {
        return workingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkBatchWokingDay.WorkingDate
     *
     * @param workingDate the value for TbIbkBatchWokingDay.WorkingDate
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    public void setWorkingDate(String workingDate) {
        this.workingDate = workingDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkBatchWokingDay.ProcStatus
     *
     * @return the value of TbIbkBatchWokingDay.ProcStatus
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    public String getProcStatus() {
        return procStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkBatchWokingDay.ProcStatus
     *
     * @param procStatus the value for TbIbkBatchWokingDay.ProcStatus
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    public void setProcStatus(String procStatus) {
        this.procStatus = procStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkBatchWokingDay.RegDate
     *
     * @return the value of TbIbkBatchWokingDay.RegDate
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkBatchWokingDay.RegDate
     *
     * @param regDate the value for TbIbkBatchWokingDay.RegDate
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkBatchWokingDay.UpdateDate
     *
     * @return the value of TbIbkBatchWokingDay.UpdateDate
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkBatchWokingDay.UpdateDate
     *
     * @param updateDate the value for TbIbkBatchWokingDay.UpdateDate
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}