package com.wadiz.client.ibk.batch.persistence;

import com.wadiz.client.ibk.batch.model.TbCampaignIbkInfo;

public interface TbCampaignIbkInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbCampaignIbkInfo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    int deleteByPrimaryKey(Integer campaignId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbCampaignIbkInfo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    int insert(TbCampaignIbkInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbCampaignIbkInfo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    int insertSelective(TbCampaignIbkInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbCampaignIbkInfo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    TbCampaignIbkInfo selectByPrimaryKey(Integer campaignId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbCampaignIbkInfo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    int updateByPrimaryKeySelective(TbCampaignIbkInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbCampaignIbkInfo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    int updateByPrimaryKey(TbCampaignIbkInfo record);
}