package com.wadiz.client.ibk.batch.persistence;

import java.util.List;

import com.wadiz.client.ibk.batch.model.TbIbkInvestRefundIfInfo;

public interface TbIbkInvestRefundIfInfoMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TbIbkInvestRefundIfInfo
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	int deleteByPrimaryKey(Integer refundId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TbIbkInvestRefundIfInfo
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	int insert(TbIbkInvestRefundIfInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TbIbkInvestRefundIfInfo
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	int insertSelective(TbIbkInvestRefundIfInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TbIbkInvestRefundIfInfo
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	TbIbkInvestRefundIfInfo selectByPrimaryKey(Integer refundId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TbIbkInvestRefundIfInfo
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	int updateByPrimaryKeySelective(TbIbkInvestRefundIfInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table TbIbkInvestRefundIfInfo
	 * @mbggenerated  Sat Jan 23 22:02:01 KST 2016
	 */
	int updateByPrimaryKey(TbIbkInvestRefundIfInfo record);

	List<TbIbkInvestRefundIfInfo> selectRefundInvestList(String stat);
	
	int updateByInvestId(TbIbkInvestRefundIfInfo record);
}