package com.wadiz.client.ibk.batch.persistence;

import com.wadiz.client.ibk.batch.model.TbInvest;

public interface TbInvestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbInvest
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    int deleteByPrimaryKey(Integer investId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbInvest
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    int insert(TbInvest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbInvest
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    int insertSelective(TbInvest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbInvest
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    TbInvest selectByPrimaryKey(Integer investId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbInvest
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    int updateByPrimaryKeySelective(TbInvest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbInvest
     *
     * @mbggenerated Sun Jan 24 15:28:06 KST 2016
     */
    int updateByPrimaryKey(TbInvest record);
}