package com.wadiz.client.ibk.batch.persistence;

import com.wadiz.client.ibk.batch.model.TbServiceHolidayInfo;
import com.wadiz.client.ibk.batch.model.TbServiceHolidayInfoKey;

public interface TbServiceHolidayInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbServiceHolidayInfo
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    int deleteByPrimaryKey(TbServiceHolidayInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbServiceHolidayInfo
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    int insert(TbServiceHolidayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbServiceHolidayInfo
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    int insertSelective(TbServiceHolidayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbServiceHolidayInfo
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    TbServiceHolidayInfo selectByPrimaryKey(TbServiceHolidayInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbServiceHolidayInfo
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    int updateByPrimaryKeySelective(TbServiceHolidayInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbServiceHolidayInfo
     *
     * @mbggenerated Thu Feb 04 13:51:45 KST 2016
     */
    int updateByPrimaryKey(TbServiceHolidayInfo record);

    /**
     * 년,월,일 로 공휴일 조회
     * @param year
     * @param month
     * @param day
     * @return
     */
	TbServiceHolidayInfo selectByYYYMMDD(String year, String month, String day);
}