package com.wadiz.client.ibk.batch.persistence;

import java.util.List;

import com.wadiz.client.ibk.batch.model.TbIbkOfferIfInfo;

public interface TbIbkOfferIfInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbIbkOfferIfInfo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    int deleteByPrimaryKey(Integer ifId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbIbkOfferIfInfo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    int insert(TbIbkOfferIfInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbIbkOfferIfInfo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    int insertSelective(TbIbkOfferIfInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbIbkOfferIfInfo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    TbIbkOfferIfInfo selectByPrimaryKey(Integer ifId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbIbkOfferIfInfo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    int updateByPrimaryKeySelective(TbIbkOfferIfInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbIbkOfferIfInfo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    int updateByPrimaryKey(TbIbkOfferIfInfo record);
    
    List<TbIbkOfferIfInfo> selectConfirmedOfferList(String date);

	int updateProcStatus(String procStatus);
}