package com.wadiz.client.ibk.batch.persistence;

import com.wadiz.client.ibk.batch.model.TbIbkBatchWokingDay;

public interface TbIbkBatchWokingDayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbIbkBatchWokingDay
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    int deleteByPrimaryKey(Integer workingNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbIbkBatchWokingDay
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    int insert(TbIbkBatchWokingDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbIbkBatchWokingDay
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    int insertSelective(TbIbkBatchWokingDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbIbkBatchWokingDay
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    TbIbkBatchWokingDay selectByPrimaryKey(Integer workingNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbIbkBatchWokingDay
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    int updateByPrimaryKeySelective(TbIbkBatchWokingDay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbIbkBatchWokingDay
     *
     * @mbggenerated Thu Feb 04 13:37:47 KST 2016
     */
    int updateByPrimaryKey(TbIbkBatchWokingDay record);

    /**
     * 작업해야하는 영업일 조회
     * @param string
     * @return
     */
	TbIbkBatchWokingDay selectWorkingdayByProcStatus(String procStatuc);
}