package com.wadiz.client.ibk.batch.model;

import java.util.Date;

import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.time.DateFormatUtils;

import com.wadiz.client.common.util.StringUtil;

public class TbIbkOfferIfInfo extends AbstractWMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.IfId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private Integer ifId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.IfCode
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String ifCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.DataType
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.Seq
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private Byte seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.BankCode
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.TranCompId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String tranCompId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.CampaignId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String campaignId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.OfferName
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String offerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.IssuCorpName
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String issuCorpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.BusinessRegNumber
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String businessRegNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.SecurtType
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String securtType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.TargetAmount
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String targetAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.PeriodStartDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String periodStartDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.PeriodFinishDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String periodFinishDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.RefundDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String refundDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.PaymentDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String paymentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.ReceiptAccountNo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String receiptAccountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.ReceiptDepositor
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String receiptDepositor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.ProcType
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String procType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.ProcStatus
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String procStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.RegDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private Date regDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.ReqDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private Date reqDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkOfferIfInfo.ResDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private Date resDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.IfId
     *
     * @return the value of TbIbkOfferIfInfo.IfId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public Integer getIfId() {
        return ifId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.IfId
     *
     * @param ifId the value for TbIbkOfferIfInfo.IfId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setIfId(Integer ifId) {
        this.ifId = ifId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.IfCode
     *
     * @return the value of TbIbkOfferIfInfo.IfCode
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getIfCode() {
        return ifCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.IfCode
     *
     * @param ifCode the value for TbIbkOfferIfInfo.IfCode
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setIfCode(String ifCode) {
        this.ifCode = ifCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.DataType
     *
     * @return the value of TbIbkOfferIfInfo.DataType
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.DataType
     *
     * @param dataType the value for TbIbkOfferIfInfo.DataType
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.Seq
     *
     * @return the value of TbIbkOfferIfInfo.Seq
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public Byte getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.Seq
     *
     * @param seq the value for TbIbkOfferIfInfo.Seq
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setSeq(Byte seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.BankCode
     *
     * @return the value of TbIbkOfferIfInfo.BankCode
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.BankCode
     *
     * @param bankCode the value for TbIbkOfferIfInfo.BankCode
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.TranCompId
     *
     * @return the value of TbIbkOfferIfInfo.TranCompId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getTranCompId() {
        return tranCompId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.TranCompId
     *
     * @param tranCompId the value for TbIbkOfferIfInfo.TranCompId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setTranCompId(String tranCompId) {
        this.tranCompId = tranCompId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.CampaignId
     *
     * @return the value of TbIbkOfferIfInfo.CampaignId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getCampaignId() {
        return campaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.CampaignId
     *
     * @param campaignId the value for TbIbkOfferIfInfo.CampaignId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setCampaignId(String campaignId) {
        this.campaignId = campaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.OfferName
     *
     * @return the value of TbIbkOfferIfInfo.OfferName
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getOfferName() {
        return offerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.OfferName
     *
     * @param offerName the value for TbIbkOfferIfInfo.OfferName
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setOfferName(String offerName) {
        this.offerName = offerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.IssuCorpName
     *
     * @return the value of TbIbkOfferIfInfo.IssuCorpName
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getIssuCorpName() {
        return issuCorpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.IssuCorpName
     *
     * @param issuCorpName the value for TbIbkOfferIfInfo.IssuCorpName
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setIssuCorpName(String issuCorpName) {
        this.issuCorpName = issuCorpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.BusinessRegNumber
     *
     * @return the value of TbIbkOfferIfInfo.BusinessRegNumber
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getBusinessRegNumber() {
        return businessRegNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.BusinessRegNumber
     *
     * @param businessRegNumber the value for TbIbkOfferIfInfo.BusinessRegNumber
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setBusinessRegNumber(String businessRegNumber) {
        this.businessRegNumber = businessRegNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.SecurtType
     *
     * @return the value of TbIbkOfferIfInfo.SecurtType
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getSecurtType() {
        return securtType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.SecurtType
     *
     * @param securtType the value for TbIbkOfferIfInfo.SecurtType
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setSecurtType(String securtType) {
        this.securtType = securtType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.TargetAmount
     *
     * @return the value of TbIbkOfferIfInfo.TargetAmount
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getTargetAmount() {
        return targetAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.TargetAmount
     *
     * @param targetAmount the value for TbIbkOfferIfInfo.TargetAmount
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setTargetAmount(String targetAmount) {
        this.targetAmount = targetAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.PeriodStartDate
     *
     * @return the value of TbIbkOfferIfInfo.PeriodStartDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getPeriodStartDate() {
        return periodStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.PeriodStartDate
     *
     * @param periodStartDate the value for TbIbkOfferIfInfo.PeriodStartDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setPeriodStartDate(String periodStartDate) {
        this.periodStartDate = periodStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.PeriodFinishDate
     *
     * @return the value of TbIbkOfferIfInfo.PeriodFinishDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getPeriodFinishDate() {
        return periodFinishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.PeriodFinishDate
     *
     * @param periodFinishDate the value for TbIbkOfferIfInfo.PeriodFinishDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setPeriodFinishDate(String periodFinishDate) {
        this.periodFinishDate = periodFinishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.RefundDate
     *
     * @return the value of TbIbkOfferIfInfo.RefundDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getRefundDate() {
        return refundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.RefundDate
     *
     * @param refundDate the value for TbIbkOfferIfInfo.RefundDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setRefundDate(String refundDate) {
        this.refundDate = refundDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.PaymentDate
     *
     * @return the value of TbIbkOfferIfInfo.PaymentDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getPaymentDate() {
        return paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.PaymentDate
     *
     * @param paymentDate the value for TbIbkOfferIfInfo.PaymentDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setPaymentDate(String paymentDate) {
        this.paymentDate = paymentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.ReceiptAccountNo
     *
     * @return the value of TbIbkOfferIfInfo.ReceiptAccountNo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getReceiptAccountNo() {
        return receiptAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.ReceiptAccountNo
     *
     * @param receiptAccountNo the value for TbIbkOfferIfInfo.ReceiptAccountNo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setReceiptAccountNo(String receiptAccountNo) {
        this.receiptAccountNo = receiptAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.ReceiptDepositor
     *
     * @return the value of TbIbkOfferIfInfo.ReceiptDepositor
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getReceiptDepositor() {
        return receiptDepositor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.ReceiptDepositor
     *
     * @param receiptDepositor the value for TbIbkOfferIfInfo.ReceiptDepositor
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setReceiptDepositor(String receiptDepositor) {
        this.receiptDepositor = receiptDepositor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.ProcType
     *
     * @return the value of TbIbkOfferIfInfo.ProcType
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getProcType() {
        return procType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.ProcType
     *
     * @param procType the value for TbIbkOfferIfInfo.ProcType
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setProcType(String procType) {
        this.procType = procType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.ProcStatus
     *
     * @return the value of TbIbkOfferIfInfo.ProcStatus
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getProcStatus() {
        return procStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.ProcStatus
     *
     * @param procStatus the value for TbIbkOfferIfInfo.ProcStatus
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setProcStatus(String procStatus) {
        this.procStatus = procStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.RegDate
     *
     * @return the value of TbIbkOfferIfInfo.RegDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.RegDate
     *
     * @param regDate the value for TbIbkOfferIfInfo.RegDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.ReqDate
     *
     * @return the value of TbIbkOfferIfInfo.ReqDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public Date getReqDate() {
        return reqDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.ReqDate
     *
     * @param reqDate the value for TbIbkOfferIfInfo.ReqDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setReqDate(Date reqDate) {
        this.reqDate = reqDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkOfferIfInfo.ResDate
     *
     * @return the value of TbIbkOfferIfInfo.ResDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public Date getResDate() {
        return resDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkOfferIfInfo.ResDate
     *
     * @param resDate the value for TbIbkOfferIfInfo.ResDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setResDate(Date resDate) {
        this.resDate = resDate;
    }

    
    public String getFiller() {
		return filler;
	}

	public void setFiller(String filler) {
		this.filler = filler;
	}


	private String filler;
    
	
	public TbIbkOfferIfInfo () {
		
		this.ifCode ="0100";
		this.bankCode = "003";			// 은행코드, 고정
		this.dataType ="05";			// 데이타구분, 고정
		this.tranCompId = "A00001";
		this.procType="00";
		this.filler = "";
		this.regDate = new Date();
		
	}
	
    @Override
	public String getMessage() {
	    	String delimeter = "";
	    	String substringOfferName = StringUtil.substringByte(offerName, 0, 40);
	    	String substringIssuCorpName = StringUtil.substringByte(issuCorpName, 0, 40);
	    	String substringreceiptDepositor = StringUtil.substringByte(receiptDepositor, 0, 40);
			return StringUtils.leftPad(ifCode,4)+delimeter
	    			+StringUtils.leftPad(dataType,2)+delimeter
	    			+StringUtils.leftPad((seq+""),7,"0")+delimeter
	    			+StringUtils.rightPad(bankCode,3)+delimeter
	    			+StringUtils.rightPad(tranCompId,6)+delimeter
	    			+StringUtils.rightPad(campaignId,8)+delimeter
	    			+StringUtils.rightPad(substringOfferName, 40-StringUtil.getHangeulCount(substringOfferName))+delimeter
	    			+StringUtils.rightPad(substringIssuCorpName, 100-StringUtil.getHangeulCount(substringIssuCorpName))+delimeter
	    			+StringUtils.rightPad(businessRegNumber,10)+delimeter
	    			+StringUtils.rightPad(securtType,2)+delimeter
	    			+StringUtils.leftPad(targetAmount,15,"0")+delimeter
	    			+StringUtils.rightPad(periodStartDate,8)+delimeter
	    			+StringUtils.rightPad(periodFinishDate,8)+delimeter
	    			+StringUtils.rightPad(refundDate,8)+delimeter
	    			+StringUtils.rightPad(paymentDate,8)+delimeter
	    			+StringUtils.rightPad(receiptAccountNo,20)+delimeter
	    			+StringUtils.rightPad(substringreceiptDepositor,50-StringUtil.getHangeulCount(substringreceiptDepositor))+delimeter
	    			+StringUtils.rightPad(procType,2)+delimeter
	    			+StringUtils.rightPad(DateFormatUtils.format(new Date(), "yyyyMMdd"),8)+delimeter
					+StringUtils.rightPad(filler, 91);
	    }
}