package com.wadiz.client.model;

import java.util.Date;

public class ClientResponse {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column response.response_seq
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	private Long responseSeq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column response.response_uuid
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	private String responseUuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column response.request_uuid
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	private String requestUuid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column response.content
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column response.reg_time
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	private Date regTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column response.response_seq
	 * @return  the value of response.response_seq
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	public Long getResponseSeq() {
		return responseSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column response.response_seq
	 * @param responseSeq  the value for response.response_seq
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	public void setResponseSeq(Long responseSeq) {
		this.responseSeq = responseSeq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column response.response_uuid
	 * @return  the value of response.response_uuid
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	public String getResponseUuid() {
		return responseUuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column response.response_uuid
	 * @param responseUuid  the value for response.response_uuid
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	public void setResponseUuid(String responseUuid) {
		this.responseUuid = responseUuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column response.request_uuid
	 * @return  the value of response.request_uuid
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	public String getRequestUuid() {
		return requestUuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column response.request_uuid
	 * @param requestUuid  the value for response.request_uuid
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	public void setRequestUuid(String requestUuid) {
		this.requestUuid = requestUuid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column response.content
	 * @return  the value of response.content
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column response.content
	 * @param content  the value for response.content
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column response.reg_time
	 * @return  the value of response.reg_time
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	public Date getRegTime() {
		return regTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column response.reg_time
	 * @param regTime  the value for response.reg_time
	 * @mbggenerated  Mon Dec 21 20:46:26 KST 2015
	 */
	public void setRegTime(Date regTime) {
		this.regTime = regTime;
	}
}