package com.wadiz.client.persistence;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.wadiz.client.model.ClientRequest;
import com.wadiz.client.model.ClientRequestExample;

public interface ClientRequestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbggenerated Mon Dec 21 19:30:25 KST 2015
     */
    int countByExample(ClientRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbggenerated Mon Dec 21 19:30:25 KST 2015
     */
    int deleteByExample(ClientRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbggenerated Mon Dec 21 19:30:25 KST 2015
     */
    int deleteByPrimaryKey(Integer requestSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbggenerated Mon Dec 21 19:30:25 KST 2015
     */
    int insert(ClientRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbggenerated Mon Dec 21 19:30:25 KST 2015
     */
    int insertSelective(ClientRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbggenerated Mon Dec 21 19:30:25 KST 2015
     */
    List<ClientRequest> selectByExample(ClientRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbggenerated Mon Dec 21 19:30:25 KST 2015
     */
    ClientRequest selectByPrimaryKey(Integer requestSeq);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbggenerated Mon Dec 21 19:30:25 KST 2015
     */
    int updateByExampleSelective(@Param("record") ClientRequest record, @Param("example") ClientRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbggenerated Mon Dec 21 19:30:25 KST 2015
     */
    int updateByExample(@Param("record") ClientRequest record, @Param("example") ClientRequestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbggenerated Mon Dec 21 19:30:25 KST 2015
     */
    int updateByPrimaryKeySelective(ClientRequest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table request
     *
     * @mbggenerated Mon Dec 21 19:30:25 KST 2015
     */
    int updateByPrimaryKey(ClientRequest record);
}