package com.wadiz.client.ibk.batch.model;

import java.util.Date;

public class TbCampaignIbkInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbCampaignIbkInfo.CampaignId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private Integer campaignId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbCampaignIbkInfo.ValidYn
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String validYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbCampaignIbkInfo.RegDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private Date regDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbCampaignIbkInfo.UpdateDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbCampaignIbkInfo.CampaignId
     *
     * @return the value of TbCampaignIbkInfo.CampaignId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public Integer getCampaignId() {
        return campaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbCampaignIbkInfo.CampaignId
     *
     * @param campaignId the value for TbCampaignIbkInfo.CampaignId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setCampaignId(Integer campaignId) {
        this.campaignId = campaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbCampaignIbkInfo.ValidYn
     *
     * @return the value of TbCampaignIbkInfo.ValidYn
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getValidYn() {
        return validYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbCampaignIbkInfo.ValidYn
     *
     * @param validYn the value for TbCampaignIbkInfo.ValidYn
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setValidYn(String validYn) {
        this.validYn = validYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbCampaignIbkInfo.RegDate
     *
     * @return the value of TbCampaignIbkInfo.RegDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbCampaignIbkInfo.RegDate
     *
     * @param regDate the value for TbCampaignIbkInfo.RegDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbCampaignIbkInfo.UpdateDate
     *
     * @return the value of TbCampaignIbkInfo.UpdateDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbCampaignIbkInfo.UpdateDate
     *
     * @param updateDate the value for TbCampaignIbkInfo.UpdateDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}