package com.wadiz.client.ibk.model;

import java.util.Date;

import org.apache.commons.lang3.StringUtils;

import com.wadiz.client.common.util.StringUtil;

public class TbIbkInvestIfInfo extends AbstractWMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkInvestIfInfo.IfId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private Integer ifId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkInvestIfInfo.IfCode
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String ifCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkInvestIfInfo.DataType
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String dataType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkInvestIfInfo.Seq
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private Byte seq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkInvestIfInfo.PayType
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkInvestIfInfo.CampaignId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String campaignId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkInvestIfInfo.OfferName
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String offerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkInvestIfInfo.InvestId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private Integer investId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkInvestIfInfo.InvestAmount
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String investAmount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkInvestIfInfo.UserId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkInvestIfInfo.PaymentsOfStocksYn
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String paymentsOfStocksYn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkInvestIfInfo.PayReqDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String payReqDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkInvestIfInfo.PayReqTime
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String payReqTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkInvestIfInfo.ProcStatus
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private String procStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkInvestIfInfo.RegDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private Date regDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkInvestIfInfo.ReqDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private Date reqDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column TbIbkInvestIfInfo.ResDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    private Date resDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkInvestIfInfo.IfId
     *
     * @return the value of TbIbkInvestIfInfo.IfId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public Integer getIfId() {
        return ifId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkInvestIfInfo.IfId
     *
     * @param ifId the value for TbIbkInvestIfInfo.IfId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setIfId(Integer ifId) {
        this.ifId = ifId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkInvestIfInfo.IfCode
     *
     * @return the value of TbIbkInvestIfInfo.IfCode
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getIfCode() {
        return ifCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkInvestIfInfo.IfCode
     *
     * @param ifCode the value for TbIbkInvestIfInfo.IfCode
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setIfCode(String ifCode) {
        this.ifCode = ifCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkInvestIfInfo.DataType
     *
     * @return the value of TbIbkInvestIfInfo.DataType
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getDataType() {
        return dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkInvestIfInfo.DataType
     *
     * @param dataType the value for TbIbkInvestIfInfo.DataType
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setDataType(String dataType) {
        this.dataType = dataType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkInvestIfInfo.Seq
     *
     * @return the value of TbIbkInvestIfInfo.Seq
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public Byte getSeq() {
        return seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkInvestIfInfo.Seq
     *
     * @param seq the value for TbIbkInvestIfInfo.Seq
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setSeq(Byte seq) {
        this.seq = seq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkInvestIfInfo.PayType
     *
     * @return the value of TbIbkInvestIfInfo.PayType
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkInvestIfInfo.PayType
     *
     * @param payType the value for TbIbkInvestIfInfo.PayType
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setPayType(String payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkInvestIfInfo.CampaignId
     *
     * @return the value of TbIbkInvestIfInfo.CampaignId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getCampaignId() {
        return campaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkInvestIfInfo.CampaignId
     *
     * @param campaignId the value for TbIbkInvestIfInfo.CampaignId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setCampaignId(String campaignId) {
        this.campaignId = campaignId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkInvestIfInfo.OfferName
     *
     * @return the value of TbIbkInvestIfInfo.OfferName
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getOfferName() {
        return offerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkInvestIfInfo.OfferName
     *
     * @param offerName the value for TbIbkInvestIfInfo.OfferName
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setOfferName(String offerName) {
        this.offerName = offerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkInvestIfInfo.InvestId
     *
     * @return the value of TbIbkInvestIfInfo.InvestId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public Integer getInvestId() {
        return investId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkInvestIfInfo.InvestId
     *
     * @param investId the value for TbIbkInvestIfInfo.InvestId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setInvestId(Integer investId) {
        this.investId = investId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkInvestIfInfo.InvestAmount
     *
     * @return the value of TbIbkInvestIfInfo.InvestAmount
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getInvestAmount() {
        return investAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkInvestIfInfo.InvestAmount
     *
     * @param investAmount the value for TbIbkInvestIfInfo.InvestAmount
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setInvestAmount(String investAmount) {
        this.investAmount = investAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkInvestIfInfo.UserId
     *
     * @return the value of TbIbkInvestIfInfo.UserId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkInvestIfInfo.UserId
     *
     * @param userId the value for TbIbkInvestIfInfo.UserId
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkInvestIfInfo.PaymentsOfStocksYn
     *
     * @return the value of TbIbkInvestIfInfo.PaymentsOfStocksYn
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getPaymentsOfStocksYn() {
        return paymentsOfStocksYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkInvestIfInfo.PaymentsOfStocksYn
     *
     * @param paymentsOfStocksYn the value for TbIbkInvestIfInfo.PaymentsOfStocksYn
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setPaymentsOfStocksYn(String paymentsOfStocksYn) {
        this.paymentsOfStocksYn = paymentsOfStocksYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkInvestIfInfo.PayReqDate
     *
     * @return the value of TbIbkInvestIfInfo.PayReqDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getPayReqDate() {
        return payReqDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkInvestIfInfo.PayReqDate
     *
     * @param payReqDate the value for TbIbkInvestIfInfo.PayReqDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setPayReqDate(String payReqDate) {
        this.payReqDate = payReqDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkInvestIfInfo.PayReqTime
     *
     * @return the value of TbIbkInvestIfInfo.PayReqTime
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getPayReqTime() {
        return payReqTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkInvestIfInfo.PayReqTime
     *
     * @param payReqTime the value for TbIbkInvestIfInfo.PayReqTime
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setPayReqTime(String payReqTime) {
        this.payReqTime = payReqTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkInvestIfInfo.ProcStatus
     *
     * @return the value of TbIbkInvestIfInfo.ProcStatus
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public String getProcStatus() {
        return procStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkInvestIfInfo.ProcStatus
     *
     * @param procStatus the value for TbIbkInvestIfInfo.ProcStatus
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setProcStatus(String procStatus) {
        this.procStatus = procStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkInvestIfInfo.RegDate
     *
     * @return the value of TbIbkInvestIfInfo.RegDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public Date getRegDate() {
        return regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkInvestIfInfo.RegDate
     *
     * @param regDate the value for TbIbkInvestIfInfo.RegDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkInvestIfInfo.ReqDate
     *
     * @return the value of TbIbkInvestIfInfo.ReqDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public Date getReqDate() {
        return reqDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkInvestIfInfo.ReqDate
     *
     * @param reqDate the value for TbIbkInvestIfInfo.ReqDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setReqDate(Date reqDate) {
        this.reqDate = reqDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column TbIbkInvestIfInfo.ResDate
     *
     * @return the value of TbIbkInvestIfInfo.ResDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public Date getResDate() {
        return resDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column TbIbkInvestIfInfo.ResDate
     *
     * @param resDate the value for TbIbkInvestIfInfo.ResDate
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    public void setResDate(Date resDate) {
        this.resDate = resDate;
    }
    
    private String resultCode;
    
	public String getResultCode() {
		return resultCode;
	}

	public void setResultCode(String resultCode) {
		this.resultCode = resultCode;
	}
	
	private String filler;
	
	public String getFiller() {
		return filler;
	}

	public void setFiller(String filler) {
		this.filler = filler;
	}
	@Override
	public String getMessage() {
	    	String delimeter = "";
	    	String substringOfferName = StringUtil.substringByte(offerName, 0, 40);
			return StringUtils.leftPad(ifCode, 4)+delimeter
	    			+StringUtils.leftPad(dataType, 2)+delimeter
	    			+StringUtils.leftPad((seq+""), 7, "0")+delimeter
	    			+StringUtils.leftPad(payType, 2)+delimeter
	    			+StringUtils.leftPad(campaignId, 8, "0")+delimeter
	    			+StringUtils.leftPad(substringOfferName, 40-StringUtil.getHangeulCount(substringOfferName))+delimeter
	    			+StringUtils.leftPad((ifId+""), 9, "0")+delimeter
	    			+StringUtils.leftPad((investId+""), 20, "0")+delimeter
	    			+StringUtils.leftPad((investId+""), 7, "0")+delimeter
	    			+StringUtils.leftPad(investAmount, 15, "0")+delimeter
	    			+StringUtils.leftPad(userId+"", 20)+delimeter
	    			+StringUtils.leftPad(paymentsOfStocksYn, 1)+delimeter
	    			+StringUtils.leftPad(payReqDate, 8)+delimeter
	    			+StringUtils.leftPad(payReqTime, 6)+delimeter
	    			+StringUtils.leftPad(filler, 51);
	    }

}