package com.wadiz.client.ibk.batch.persistence;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.wadiz.client.ibk.batch.model.TbIbkInvestIfInfo;

public interface TbIbkInvestIfInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbIbkInvestIfInfo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    int deleteByPrimaryKey(Integer ifId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbIbkInvestIfInfo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    int insert(TbIbkInvestIfInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbIbkInvestIfInfo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    int insertSelective(TbIbkInvestIfInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbIbkInvestIfInfo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    TbIbkInvestIfInfo selectByPrimaryKey(Integer ifId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbIbkInvestIfInfo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    int updateByPrimaryKeySelective(TbIbkInvestIfInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TbIbkInvestIfInfo
     *
     * @mbggenerated Wed Jan 06 16:00:21 KST 2016
     */
    int updateByPrimaryKey(TbIbkInvestIfInfo record);

	List<TbIbkInvestIfInfo> selectSbcrList(@Param("payType") String payType, @Param("date") String date);

	int updateProcStatus(String procStatus);

	TbIbkInvestIfInfo selectInvestIfInfo(int investId);

	int updateResultInvest(TbIbkInvestIfInfo resultInvest);

	List<TbIbkInvestIfInfo> selectCompletedInvestList(int campaignId);
}